[package]
name = "packet-capture"
version = "0.1.0"
authors = ["monmaru"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.22.0"

